<a href="https://colab.research.google.com/github/SimonThoabaladev/7-Se/blob/main/1_ex_0101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Coding Exercise 0101

### 1. NumPy library:

#### 1.1. NumPy basics:

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
type(arr1)

numpy.ndarray

In [ ]:
arr3 = arr1

In [ ]:
id(arr1)

133483335448976

In [ ]:
id(arr3)

133483335448976

In [ ]:
arr4 = arr1.copy()

In [ ]:
id(arr4)

133483324980848

#### 1.2. Creating NumPy arrays:

numpy.arange() function:

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [ ]:
arr = np.arange(10)

In [ ]:
len(arr)

10

In [ ]:
arr.size

10

numpy.linspace() function:

In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr = np.linspace(0, 10, 5, retstep=True)
type(arr)

tuple

In [ ]:
arr[0]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
arr[1]

2.5

numpy.zeros() and numpy.ones() functions:

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros(5, dtype ='int64')

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(5, dtype ='int64').dtype

dtype('int64')

In [ ]:
arr = np.ones((2,3), dtype ='int_')

In [ ]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr.dtype

NameError: name 'arr' is not defined

In [ ]:
arr.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

Data type:

In [ ]:
arr1 = np.array([111, 2.3,  True, False, False])
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [ ]:
arr2 = np.array([111, 2.3, 'python', 'abc'])
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [ ]:
arr3 = np.array([111, True, 'abc'])
arr3

array(['111', 'True', 'abc'], dtype='<U21')

#### 1.3. Indexing and slicing NumPy arrays:

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [ ]:
a[-1]

5

In [ ]:
a[:]

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[1]

array([4, 5, 6])

In [ ]:
a[-1]

array([7, 8, 9])

In [ ]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[2][1]

8

In [ ]:
a[2,1]

8

In [ ]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

Fancy indexing:

In [ ]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 )
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

#### 1.4. NumPy attributes and reshaping:

In [ ]:
a.size

9

In [ ]:
a.shape

(3, 3)

In [ ]:
a.ndim

2

Change the shape with reshape() method:

In [ ]:
a = np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# reshape() just produced a 'view'.
# So, there is no permanent change to 'a'.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [ ]:
a = a.reshape((2,2))
a

array([[2, 5],
       [1, 3]])

Careful that the reshape() method does not create a new object!

In [ ]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999

In [ ]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
# Make a copy in order to create a new object.
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

#### 1.5. Modifying NumPy arrays:

Appending elements, rows and columns to arrays:

In [ ]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [ ]:
c = np.append(a, [[9], [9]] , axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

Deleting array elements, rows and columns:

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [ ]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [ ]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [ ]:
np.delete(a, 1, axis = 1)

array([[1, 3],
       [4, 6]])