<a href="https://colab.research.google.com/github/SimonThoabaladev/7-Se/blob/main/4_ex_0103b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array Transposition

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr=np.random.randn(6,3)
arr

array([[ 0.69428463,  1.14677701,  0.11248345],
       [ 1.97400742, -1.15903778,  2.38399561],
       [ 1.09961441,  0.15245658,  1.67770613],
       [ 0.62153864, -0.93067544,  0.18524128],
       [-1.95809057,  0.80279215,  0.48867634],
       [-0.96271398, -0.45299011, -0.27497076]])

In [ ]:
np.dot(arr.T, arr)

array([[10.73513547, -3.03840665,  6.05193065],
       [-3.03840665,  4.39754114, -2.03390515],
       [ 6.05193065, -2.03390515,  8.85951326]])

In [ ]:
arr=np.arange(16).reshape(2,2,4)

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])